# Generated by Django 2.2 on 2021-11-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_code', models.CharField(max_length=5)),
                ('building_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floors_at_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_floors', to='office_space_app.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=5)),
                ('building_code', models.CharField(max_length=5)),
                ('floor_code', models.CharField(max_length=5)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('Location_anchor', 'Location_anchor'), ('Building_anchor', 'Building_anchor'), ('Floor_anchor', 'Floor_anchor')], max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_users', to='office_space_app.Building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_users', to='office_space_app.Floor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_users', to='office_space_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=25)),
                ('seat_type', models.CharField(max_length=45)),
                ('floor_code', models.CharField(max_length=5)),
                ('building_code', models.CharField(max_length=5)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats_at_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_seats', to='office_space_app.Building')),
                ('seats_at_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_seats', to='office_space_app.Floor')),
                ('seats_at_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_seats', to='office_space_app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='floors_at_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_floors', to='office_space_app.Location'),
        ),
        migrations.AddField(
            model_name='building',
            name='buildings_at_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_buildings', to='office_space_app.Location'),
        ),
    ]
