# Generated by Django 2.2 on 2021-11-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_space_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='buildings_at_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='floors_at_building',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='floors_at_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_building',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_floor',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Manager_cabin', 'Manager_cabin')], max_length=45),
        ),
    ]
