# Generated by Django 3.2.9 on 2021-11-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_space_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='buildings_at_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='floors_at_building',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='floors_at_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_building',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_floor',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seats_at_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='user',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_users', to='office_space_app.building'),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='floor_users', to='office_space_app.floor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_users', to='office_space_app.location'),
        ),
    ]
