# Generated by Django 2.2 on 2021-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_space_app', '0002_auto_20211106_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_anchor',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Location_anchor', 'Location_anchor'), ('Building_anchor', 'Building_anchor'), ('Floor_anchor', 'Floor_anchor')], max_length=45),
        ),
    ]
