# Generated by Django 2.2 on 2021-11-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_space_app', '0003_auto_20211107_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_buildings', to='office_space_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_code', models.CharField(max_length=5)),
                ('building_code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_floors', to='office_space_app.Building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_floors', to='office_space_app.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_users', to='office_space_app.Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Location_anchor', 'Location_anchor'), ('Building_anchor', 'Building_anchor'), ('Floor_anchor', 'Floor_anchor')], max_length=45),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=25)),
                ('seat_type', models.CharField(max_length=45)),
                ('floor_code', models.CharField(max_length=5)),
                ('building_code', models.CharField(max_length=5)),
                ('location_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_seats', to='office_space_app.Building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_seats', to='office_space_app.Floor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_seats', to='office_space_app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='building_users', to='office_space_app.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='floor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='floor_users', to='office_space_app.Floor'),
            preserve_default=False,
        ),
    ]
