# Generated by Django 2.2 on 2021-11-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_space_app', '0004_auto_20211110_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='building',
        ),
        migrations.RemoveField(
            model_name='user',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
